### ISSUE TITLE
Solution to including Board.cpp in Piece.cpp. Basis for overriding isValidMove for all pieces. High priority

### ISSUE THREAD

**Issue by finicu212** [finicu212/openChess#24]
Instead of referencing the global board object in Piece.cpp, do this:

- Move class should contain an uint8_t (unsigned char) field which contains the type of move. I can currently think of the following types: ( To be revised in the future )

0. if no piece at dest square

1. (CAPTURING MOVE) if different color piece at dest square

255. if same color piece at dest square EDIT: this is actually an invalid move. set the char to value 255? to be revised

---

The following should be done in a separate PR, and will be listed in a separate issue soon:

3. (EN PASSANT) - if: moving pawn from source square, no piece at dest square, but enemy pawn did two moves over this square in the previous turn

4. (CASTLING) - if: trying to move king two squares towards left / right. king hasn't moved at all yet. rook to the left / right exists and hasn't moved at all yet. no enemy piece has direct line of sight on any of the squares between and including rook and king.

---

- Board should have an Move updateMove(Move) method which initializes the unsigned char talked about before and returns a Move object. 

- Board should provide a method isValidMove(Move) which calls isValidMove(Move) on the piece at Move.origin

**Comment by eiTi3Aishieg** [comment]
Bobeh approves this PR great job
